### ISSUE TITLE
Cours 3 : raccourcir le nom du fichier gff3 utiliser en exemple

### ISSUE THREAD

**Issue by pierrepo** [DU-Bii/module-1-Environnement-Unix#1]
Nom du fichier : 
`Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.37.chromosome.Chromosome.gff3`

To do : 
- [ ] trouver un nom plus court
- [ ] mettre à jour le tutoriel (et les solutions)
- [ ] mettre à jour le fichier dans le dépôt `study-cases`

**Comment by jvanheld** [comment]
Le nom de fichier est important pour la traçabilité. Il est téléchargé directement à partir d'EnsemblGenomes, et chaque élément du nom est nécessaire pour le distinguer des autres fichiers.

Par ailleurs pour un tuto c'est très peu didactique. 

Solutions: 

- renommer le fichier mais conserver dans le script le téléchargement du fichier original
- conserver le fichier original et créer un lien logique avec un nom court (le beurre et l'argent du beurre)

```
ln -s Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.37.chromosome.Chromosome.gff3 Ecoli_annotations.gff3
```

Une préférence ?

**Comment by pierrepo** [comment]
La solution 1 
>renommer le fichier mais conserver dans le script le téléchargement du fichier original

me semble la plus pertinente.

Je souhaite évite les liens autant que possible, d'autant plus qu'ils n'ont pas été introduits aux stagiares.

**Comment by benoistlaurent** [comment]
Pas sûr d'avoir compris la solution 1.
Est-ce que l'idée est de demander aux étudiants de télécharger le fichier eux-mêmes et de le renommer après ?

Au passage, j'aimais bien la solution 2. Personnellement je fais ça assez régulièrement de mettre un lien avec un nom plus court pour montrer qu'en fait il s'agit d'un autre fichier qui est ailleurs et qui a un nom plus malin que ça.
Par exemple :

```bash
$ ls -lh
lrwxr-xr-x 1 benoist staff 92 Feb 24 19:11 input.pdb -> /Users/benoist/project_SUFII/raw_pdb/1aaa_this_file_has_a_very_long_name_for_some_reason.pdb
```

Cela dit je crois qu'on avait déjà discuté du fait qu'on n'avait pas trop le temps de présenter les liens. Par conséquent, effectivement la solution 1 (que je n'ai pas comprise) est probablement meilleure.

**Comment by pierrepo** [comment]
Bref. Autant garder le nom long.
