### ISSUE TITLE
Automatisation : bonnes pratiques entête script

### ISSUE THREAD

**Issue by pierrepo** [DU-Bii/module-1-Environnement-Unix#10]
Pour éviter des mauvaises surprises, les bonnes pratiques Bash recommandent de mettre ces lignes au début du script : 

```
set -o nounset    # abort if variable is not defined
set -o errexit    # abort if command fails
set -o pipefail   # abort if pipe fails
```

Je suggère que nous les mettions aussi dans nos scripts

**Comment by benoistlaurent** [comment]
Fixed (7c89d67).

Pour que les diapos restent lisibles, j'ai rajouté une diapo pour montrer comment on fait.
Dans le reste des diapos, rien ne change (3 lignes de code ça fait beaucoup sur une diapo).

OK ?

**Comment by pierrepo** [comment]
OK. Parfait @benoistlaurent  ;-)
