### ISSUE TITLE
Supprimer les numéros des questions

### ISSUE THREAD

**Issue by pierrepo** [DU-Bii/module-1-Environnement-Unix#3]
Pour pouvoir insérer de nouvelles questions plus facilement.

**Comment by benoistlaurent** [comment]
Je vois très bien l'intérêt. D'un autre côté ça permet de bien se repérer dans la séance : "faites les questions 1 et 2 pour demain". 
Décision ?

**Comment by pierrepo** [comment]
Tu as parfaitement raison, il faut conserver les numéros de questions. Pour éviter de renuméroter toutes les questions quand on en introduit une nouvelle, j'ai découpé le tuto de la séance 1 en plusieurs parties. Je te laisse jeter un oeil.
