### ISSUE TITLE
Add tutorial for SSH connexion and file transfert

### ISSUE THREAD

**Issue by pierrepo** [DU-Bii/module-1-Environnement-Unix#5]
Create a tutorial page with:
- SSH connexion to the server
- Copy file to and from the cluster with scp
- Transfer files with rsync and FileZilla.

Provide examples for all OS.

**Comment by pierrepo** [comment]
See also: https://ifb-elixirfr.gitlab.io/cluster/doc/logging-in/

**Comment by benoistlaurent** [comment]
Also move this part from session 2 to supplementary material

**Comment by benoistlaurent** [comment]
1. Qui fait ça ?!
2. Est-ce que c'est juste pour dire aux étudiants "regardez tel document qui explique comment on fait" où l'idée serait de l'aborder à un moment ?
3. Si je comprends, bien, et s'il doit y avoir des exemples qui fonctionnent dans ce tuto, les exemples seraient en ce connectant au cluster de l'IFB depuis leur machine, par opposition à "depuis le JupyterHub".

**Comment by pierrepo** [comment]
L'organisation de cet aspect n'est pas encore complètement claire pour moi.
Mais j'avais en tête qu'on montre concrètement aux apprenants comment se connecter en SSH au serveur de calcul (depuis les machines locales) et comment envoyer et récupérer des données.

**Comment by benoistlaurent** [comment]
Oui ça me semblerait utile aussi.
En revanche eux ne pourront le faire que s'ils ont un "vrai" terminal à
côté d'eux.

Arrêtez moi si je me trompe mais ça m'étonnerait qu'ils puissent faire un
ssh sur le master depuis un nœud (jupyterhub tourne sur un nœud)

**Comment by pierrepo** [comment]
> En revanche eux ne pourront le faire que s'ils ont un "vrai" terminal à côté d'eux.

Tout à fait. Depuis les salles informatiques, ils pourront ouvrir un terminal et tester les connexions.

> mais ça m'étonnerait qu'ils puissent faire un ssh sur le master depuis un nœud (jupyterhub tourne sur un nœud)

Effectivement, on ne peut pas faire de SSH depuis un noeud sur le master mais on peut faire un SSH depuis un noeud vers un autre serveur SSH (ailleurs dans le monde par exemple).

**Comment by benoistlaurent** [comment]
> on peut faire un SSH depuis un noeud vers un autre serveur SSH (ailleurs dans le monde par exemple).
C'est bien pratique ça !

Conclusion : il faut définir

- [ ] qui fait ça 
- [ ] sous quelle forme 
- [ ] à quelle machine distance on se connecte

**Comment by pierrepo** [comment]
>on peut faire un SSH depuis un noeud vers un autre serveur SSH (ailleurs dans le monde par exemple).

Pratique mais on ne va pas faire. C'est trop lourd à organiser.

La connexion SSH se fera depuis une machine locale (des salles info) vers le cluster IFB.

Voici des exemples de manipulations qui pourraient être réalisées : 

1. Connexion SSH depuis un terminal de la machine locale vers le cluster IFB. Les apprenants vérifient que les fichiers de leur répertoire perso sont bien présents. Par exemple vérifier que le répertoire `study-cases` est bien présent dans le répertoire `dubii` créé lors de la toute première séance.

2. Copie d'un fichier puis d'un répertoire avec `scp` depuis le serveur IFB vers la machine locale (on peut prendre des fichiers et répertoire dans `~/dubii/study-cases/`)

3. Modification ou création d'un fichier local.

4. Copie de ce fichier local sur le cluster de l'IFB, toujours avec `scp`

5. Synchro avec rsync. Par exemple pour rappatrier `~/dubbi/study-cases` sur la machine locale.

> qui fait ça

À voir avec @hchiapello et toi.

**Comment by pierrepo** [comment]
On peut aussi clôturer cette issue @benoistlaurent / @hchiapello ?
