### ISSUE TITLE
Supprimer question 7 tuto flux

### ISSUE THREAD

**Issue by benoistlaurent** [DU-Bii/module-1-Environnement-Unix#6]
Cette question sera traitée à la séance 1

**Comment by benoistlaurent** [comment]
@pierrepo À ce moment là, supprimer toute la partie 2.3, non ?

**Comment by pierrepo** [comment]
Non, car dans la séance 1, on ne traite que des redirections avec `<` et `>`. Le pipe `|` n'est pas pertinent à ce moment-là. 

La notion de pipe devient intéressante dans la séance 2 quand on combine plusieurs outils. Peut-être que tu peux raccourcir la partie cours sur les redirections, virer la question 7 et discuter directement du pipe.

**Comment by benoistlaurent** [comment]
Ça marche.

**Comment by pierrepo** [comment]
@benoistlaurent on peut fermer cette issue, non ?
