### ISSUE TITLE
Automatisation : appel du script

### ISSUE THREAD

**Issue by pierrepo** [DU-Bii/module-1-Environnement-Unix#8]
Je préfère qu'on appelle un script Bash explicitement par son interpréteur : 
```
bash toto.sh
```
plutôt que 
```
./toto.sh
```
Cela évite de rendre le script exécutable avec la commande `chmod`. C'est aussi consistant avec ce qui peut être fait en Python `python toto.py` ou en R `Rscript toto.R`

**Comment by benoistlaurent** [comment]
Fixed (3a4b430). Dans le tuto, on explique comment on fait pour faire `./toto.bash` mais dans tous le reste du document c'est la méthode `bash toto.bash` qui est utilisée.
