### ISSUE TITLE
Automatisation : test

### ISSUE THREAD

**Issue by pierrepo** [DU-Bii/module-1-Environnement-Unix#9]
La bonne pratique est désormais utiliser `[[ ]]` plutôt que `[ ]` pour les tests.

>`[[` is bash's improvement to the `[` command. It has several enhancements that make it a better choice if you write scripts that target bash. 

- http://robertmuth.blogspot.com/2012/08/better-bash-scripting-in-15-minutes.html
- https://www.youtube.com/watch?v=m5vKQ7ATBNc
- https://stackoverflow.com/questions/3427872/whats-the-difference-between-and-in-bash

**Comment by benoistlaurent** [comment]
Fixed (568500b).
